import Head from 'next/head'

import { Inter } from '@next/font/google'
import { useEffect, useState } from 'react'
import ScheduleComponent from '../components/schedule/ScheduleComponent'
import { IGame, ISchedule } from '../types/ISchedule'
import { CircularProgress, Container } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [loading, setLoading] = useState<boolean>(false);
  const [schedule, setSchedule] = useState<{[key: string]: Array<IGame>} | null>(null);

  useEffect(() => {
    setLoading(true);
    const getSchedule = async(scheduleId: string) => {
      await fetch(`/api/schedule/${scheduleId}`)
        .then((response) => response.json() as Promise <{schedule: {[key: string]: Array<IGame>}, date: Date}>)
        .then((data) => {
          setSchedule(data.schedule);
        }).finally(() => setLoading(false));
    }
    getSchedule('some-schedule-id');
  }, [])

  if(loading) {
    return <CircularProgress/>
  }

  if(!schedule) {
    return <>No Schedule Found!</>
  }



  const scheduleVM = Object.entries(schedule).map((section) => {
    return {
        header: section[0],
        games: section[1],
    }
  });

  return (
    <>
      <Head>
        <title>Game Changer App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container sx={{mt: 4}}>
          <ScheduleComponent schedule={scheduleVM} />
        </Container>
      </main>
    </>
  )
}
